Refactor : #12 로그인 기능 리펙터링 수행
BaeJunH0/AlumniLink_BE pull request #13
Opened 2024-11-21 12:04 UTC by BaeJunH0

## PR 제목

### 구현 내용

- .properties 파일에 .env 파일 경로 및 config 문 작성
- Value 어노테이션으로 매핑되는 변수 및 이를 사용하는 메서드 static -> non-static 변경
- jwt 토큰 생성 클래스의 상위 디렉토리명 util -> token
- jwt 토큰 생성 클래스 사용을 모두 static -> 객체 생성 후 사용으로 변경
- Entity 객체에 Entity 및 Table 어노테이션 삽입
- 비즈니스 로직 변경 ( 로그인 체크 )

### 구현 이유

- 값을 읽지 못하는 문제를 해결하기 위해
- static의 경우 Value 어노테이션으로 대입이 불가
- 더 이상 Util 클래스가 아니개 되어서
- 더 이상 Static 메서드가 아니게 되어서
- ORM 사용을 위해
- 로그인 검사 과정에서 맞으면 틀리고, 틀리면 맞는 논리적 문제가 생겨서

### 버그 리포트

- 로그인 시, 비밀번호가 틀리면 맞다고 판단하고 맞으면 틀리다고 판단하는 버그가 있었음 -> 해결 완료

2024-11-21 14:15 UTC, jbh010204 requested changes
테스트 코드 작성 부탁드립니다.

2024-11-21 14:15 UTC, jbh010204 commented on src/main/java/com/sparksInTheStep/webBoard/auth/presentation/UserController.java
> +        String accessToken = jwtTokenProvider.makeAccessToken(userRequest.nickname());
Util을 JwtTokenProvider로 바꾼 이유가 무엇인가요?

2024-11-21 14:22 UTC, BaeJunH0 commented on src/main/java/com/sparksInTheStep/webBoard/auth/presentation/UserController.java
> +        String accessToken = jwtTokenProvider.makeAccessToken(userRequest.nickname());
[참고](https://velog.io/@baejunh0/Util-Class) <- 제가 쓴 Util 클래스 관련 글이에요
Util 클래스는 모든 method가 static하고, 객체 생성이 금지된, 오직 기능만을 위한 클래스인데, static 방식 변수 선언으로는 @Value를 통한 환경 변수 매핑이 불가능하다는 것을 알게되어서 이를 수정했어요
그래서 JwtUtil이 더 이상 Util 클래스가 아니게 되어서 해당 클래스와, 상위 디렉토리의 이름을 Util에서 토큰 관련된 이름으로 바꾸었어요 ^^

2024-11-22 13:42 UTC, jbh010204 approved these changes
클린 코드하네요~

2024-11-22 13:42 UTC, merged